* Getting Started

  This is the first attempt to create a repository for =dotfiles= and an
  install script to make all the necesary changes.

  To clone this repository, from prompt use:

#+BEGIN_SRC sh
git clone https://github.com/userzc/.dotfiles.git
cd .dotfiles
git submodule sync
git submodule update --init --recursive
#+END_SRC

** Instalation

   To install the files in this repository use:

#+BEGIN_SRC sh
python ~/.dotfiles/sync -i
#+END_SRC

   On Windows the script must be run as administrator.

** Quick basic environment

   To install some usefull features and get emacs and other googies as
   soon as possible use:

#+begin_src sh
curl -L https:/github.com/userzc/.dotfiles/raw/master/basic_environ.sh | sh
#+end_src

*** Note:

    Currently this only works on *Ubuntu 14.04*, later on
    compatibility with other distributions may be added as I use them.

** Requirements

   | Software         | Windows Version | Prefered Source [W] | Unix Version | Prefered Source [U] |
   |------------------+-----------------+---------------------+--------------+---------------------|
   | Emacs            | >= 24           | chocolatey          |        >= 24 | standard repo       |
   | Inconsolata Font | ---             | ---                 |    001.010-4 | standard repo       |
   | python           | >= 3.2          | chocolatey          |       >= 2.7 | standard repo       |
   | git              | ---             | chocolatey          |      1.8.3.2 | standard repo       |
   | quickswitch-i3   | ---             | ---                 |          2.0 | pip (PyPI)          |
   | rope             | 0.9.4           | pip (PyPI)          |        0.9.4 | pip (PyPI)          |
   | ropemacs         | 0.7             | pip (PyPI)          |          0.7 | pip (PyPI)          |
   | ropemode         | 0.2             | pip (PyPI)          |          0.2 | pip (PyPI)          |
   | texlive          | ---             | ---                 |         2012 | standard repo       |
   | eclim            | 2.3.4           | [[http://eclim.org][eclim]]               |        2.3.2 | [[http://eclim.org][eclim]]               |
   | eclipse          | Kepler          | [[http://eclipse.org][eclipse]]             |       Kepler | [[http://eclipse.org][eclipse]]             |
   | java             | 1.7 Oracle      | chocolatey          |   1.7 Oracle | [[https://launchpad.net/~webupd8team/+archive/java][webupd8 ppa]]         |
   | groovy           | NA              | NA                  |        2.2.1 | [[http://gvmtool.net/][gvm]]                 |
   | maven            | 3.0.5           | chocolatey          |        3.0.4 | standard repo       |

*** Note on Ubuntu

    *pip* was globally installed as in the instructions in it's [[https://pip.pypa.io/en/latest/installing.html#install-pip][Documentation]],
    and used to install *virtualenv* and *virtualenvwrapper* globally.

    If using [[http://i3wm.org/][i3wm]] (as this configuration assumes), it may seem a good
    idea to [[http://askubuntu.com/questions/108925/how-to-tell-chrome-what-to-do-with-a-magnet-link][change xdg-open]] to open magnet and torrent files from the
    web browser.

*** Note on Windows

    It is recommended that most windows packages are installed through
    [[http://chocolatey.org][chocolatey]] since this facilitates the process, in particular
    install packages.

    So far the installation of *maven* facilitates the use of *malabar*
    mode in Windows, however work still needs to be done to
    get *eclimd* working properly.

*** Note on Java related software

    Most java software on ubuntu was installed manually:

    - eclipse was installed using the turorial [[http://akovid.blogspot.mx/2012/08/installing-eclipse-juno-42-in-ubuntu.html][installing eclipse on Ubuntu]].
    - eclim was installed following the [[http://eclim.org/install.html][installation instructions]] from
      the official webpage.
    - groovy was also installed using the [[http://gvmtool.net/][installation instructions]]
      from the official webpage.

** Features

   So far this script is able to =symlink= files and folders under some
   specific lists and special cases (=.config/= folder).

   This script accepts options for install (=-i=, =--install=), listing
   the posible files to modify (=-l=, =--list=) and for removal of the
   existing links or files (=-r=, =--remove=). The script is installing
   files through python, so it should also be portable to windows.

# Local Variables:
# eval: (orgtbl-mode t)
# End:
