(source gnu)
(source melpa)

(package "defuns" "0.0.1"
         "Testing cask for emacs lisp development on personal functions.")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "espuds")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
